# Generated by Django 4.2.6 on 2023-10-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='codigo',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
