# Generated by Django 4.2.7 on 2023-11-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="observacion",
        ),
        migrations.AddField(
            model_name="pedido",
            name="cliente",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="producen",
            name="producto_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.pedido"
            ),
        ),
    ]
