# Generated by Django 4.2.6 on 2023-10-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(blank=True, default='True', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='estado',
            field=models.CharField(blank=True, default='True', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, default='True', max_length=50, null=True),
        ),
    ]
