# Generated by Django 4.2.6 on 2023-10-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_compra_estado_alter_ingresos_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_produccion',
        ),
    ]
