# Generated by Django 4.2.7 on 2023-11-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_pedido_compra_id_remove_pedido_empleado_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cliente", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("cuotas", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_creacion", models.DateField(blank=True, null=True)),
                ("fecha_modificacion", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "venta",
            },
        ),
        migrations.RemoveField(
            model_name="producen",
            name="empleado_id",
        ),
        migrations.RemoveField(
            model_name="producen",
            name="producto_id",
        ),
        migrations.DeleteModel(
            name="Lineadetalle",
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
        migrations.DeleteModel(
            name="Producen",
        ),
    ]
