# Generated by Django 4.2.7 on 2023-11-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_pedido"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pedido",
        ),
    ]
