# Generated by Django 4.2.7 on 2023-11-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_delete_pedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cliente", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, default="True", max_length=50, null=True
                    ),
                ),
                ("fecha_creacion", models.DateField(blank=True, null=True)),
                ("fecha_modificacion", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "pedido",
            },
        ),
    ]
