# Generated by Django 4.2.7 on 2023-11-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pedido_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=20, null=True),
        ),
    ]
