# Generated by Django 4.2.6 on 2023-11-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_proveedor_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
