# Generated by Django 4.2.6 on 2023-11-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_apellido_cliente_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=20, null=True),
        ),
    ]
