# Generated by Django 4.2.7 on 2023-11-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_lineapedido_pedido_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cuotas',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.DeleteModel(
            name='Cuotas',
        ),
    ]
