# Generated by Django 4.2.7 on 2023-11-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pedido_cuotas_delete_cuotas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='lote',
            new_name='cod_barra',
        ),
    ]
