# Generated by Django 4.2.7 on 2023-11-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_lote_producto_cod_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_comprobante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
